(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
phi=N[GoldenRatio];
rad=First[x/. N[Solve[Tan[72 \[Degree]] x==1-2 x,x]]];
toppoint=N[{1/2,Sin[72 \[Degree]] phi}];
starttriangle={toppoint,{1,0.},{0.,0.},1};


(* ::Input::Initialization:: *)
dissect[{p_,q_,r_,1}]:=(newpoint=(phi q+p) (2-phi);{{r,newpoint,q,1},{r,newpoint,p,-1}})
dissect[{p_,q_,r_,-1}]:=(newpoint=(phi r+p) (2-phi);{{r,newpoint,q,-1},{p,q,newpoint,1}})
dissect[list_]:=(type*=-1;Join[Select[list,Last[#1]!=type&],Flatten[dissect/@Select[list,Last[#1]==type&],1]]/;TensorRank[list]!=1)


(* ::Input::Initialization:: *)
Triangles[n_]:=(type=1;tiles=Nest[dissect,starttriangle,n]/. 
{p_,q_,r_,x_}->{Red,Line[{q,r,p}],Thickness[.0005],Line[{p,q}]};
Show[Graphics[{Blue,Thickness[.0005],tiles}],AspectRatio->1,PlotRange->{{rad,1-rad},{0,1-2 rad}}])
Attributes[TriangleDisection]=Listable;


(* ::Input::Initialization:: *)
Kites[n_]:=(type=1;tiles=Nest[dissect,starttriangle,2 n]/.
 {{p_,q_,r_,-1}->Line[{q,r,p}],{p_,q_,r_,1}->{Line[{q,r,p}]}};
Show[Graphics[{Magenta,Thickness[.0005],tiles}],AspectRatio->1,PlotRange->{{rad,1-rad},{0,1-2 rad}}])
Attributes[Kites]=Listable;


(* ::Input::Initialization:: *)
Rhombs[n_]:=(type=1;tiles=Nest[dissect,starttriangle,2 n+1]/. 
{{p_,q_,r_,1}->Line[{r,p,q}],{p_,q_,r_,-1}->Line[{p,q,r}]};
Show[Graphics[{Purple,Thickness[.003],tiles}],AspectRatio->1,PlotRange->{{rad,1-rad},{0,1-2 rad}}])
Attributes[Rhombs]=Listable;


(* ::Input::Initialization:: *)
arrow[{{x1_,y1_},{x2_,y2_}}]:=Block[{sum,dif,norm,normal},
sum={x1+x2,y1+y2};
dif={x2-x1,y2-y1};
norm=Sqrt[dif.dif];
normal={{0,1},{-1,0}}.dif/norm;
{
Line[{{x1,y1},{x2,y2}}],
Line[{sum/2,-(dif/20)+(norm normal)/20+sum/2}],
Line[{sum/2,-(dif/20)-(norm normal)/20+sum/2}]
}]


(* ::Input::Initialization:: *)
twoarrow[{{x1_,y1_},{x2_,y2_}}]:=Block[{su46,su54,para,dif,norm,normal},
para=46/100;
su46=para {x1,y1}+(1-para) {x2,y2};
su54=(1-para) {x1,y1}+para {x2,y2};
dif={x2-x1,y2-y1};
norm=Sqrt[dif.dif];normal={{0,1},{-1,0}}.dif/norm;
{
Line[{{x1,y1},{x2,y2}}],
Line[{su46,-(dif/20)+(norm normal)/20+su46}],
Line[{su46,-(dif/20)-(norm normal)/20+su46}],
Line[{su54,-(dif/20)+(norm normal)/20+su54}],
Line[{su54,-(dif/20)-(norm normal)/20+su54}]
}]


(* ::Input::Initialization:: *)
ARhombs[n_]:=(type=1;tiles=Nest[dissect,starttriangle,2 n+1]/.
 {
{p_,q_,r_,1}->{arrow[{p,q}],twoarrow[{p,r}]},
{p_,q_,r_,-1}->{arrow[{p,q}],twoarrow[{q,r}]}
};
Show[Graphics[{Red,Thickness[.0015],tiles}],AspectRatio->1,PlotRange->{{rad,1-rad},{0,1-2 rad}}])
Attributes[ARhombs]=Listable;


(* ::Input::Initialization:: *)
fac=20;
unitcircle=Table[N[{Sin[(2 \[Pi] n)/fac],Cos[(2 \[Pi] n)/fac]}],{n,fac+1}];


(* ::Input::Initialization:: *)
circle[{p_,q_},r_]:=({p,q}+r #1&)/@unitcircle;


(* ::Input::Initialization:: *)
openopen[{x1_,y1_},{x2_,y2_}]:=Block[{vec,start,end,norm},
vec={x2-x1,y2-y1};norm=Sqrt[vec.vec];
start={x1,y1}+vec/20;end={x2,y2}-vec/20;
{Blue,Line[{start,end}],Line[circle[{x1,y1},norm/20]],Line[circle[{x2,y2},norm/20]]}]
openclose[{x1_,y1_},{x2_,y2_},sc_]:=Block[{vec,start,end,norm},
vec={x2-x1,y2-y1};
norm=Sqrt[vec.vec];start={x1,y1}+(sc vec)/20;
end={x2,y2}-(sc vec)/20;
{Line[{start,end}],Line[circle[{x1,y1},(sc norm)/20]],Polygon[circle[{x2,y2},(sc norm)/20]]}]


(* ::Input::Initialization:: *)
closeopen[{x1_,y1_},{x2_,y2_},sc_]:=Block[{vec,start,end,norm},
vec={x2-x1,y2-y1};
norm=Sqrt[vec.vec];
start={x1,y1}+(sc vec)/20;
end={x2,y2}-(sc vec)/20;
{Purple,Line[{start,end}],Polygon[circle[{x1,y1},(sc norm)/20]],Line[circle[{x2,y2},(sc norm)/20]]}]


(* ::Input::Initialization:: *)
closeclose[{x1_,y1_},{x2_,y2_}]:=Block[{vec,start,end,norm},
vec={x2-x1,y2-y1};
norm=Sqrt[vec.vec];
start={x1,y1}+vec/20;
end={x2,y2}-vec/20;
{Magenta,Line[{start,end}],Polygon[circle[{x1,y1},norm/20]],Polygon[circle[{x2,y2},norm/20]]}]


(* ::Input::Initialization:: *)
CKites[n_]:=(type=1;tiles=Nest[dissect,starttriangle,2 n]/. 
{{p_,q_,r_,-1}->{openclose[q,r,1],closeopen[r,p,1/phi]},
{p_,q_,r_,1}->{closeopen[q,r,1],openclose[r,p,1/phi]}};
Show[Graphics[{Red,Thickness[.0005],tiles}],AspectRatio->1,PlotRange->{{rad,1-rad},{0,1-2 rad}}])



